### ISSUE TITLE
Get historical status based on provided date

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#211]
The sample/project status relies on the set of LIMS steps finished at the time of the query.
It should be possible to calculate the status at previous time points by limiting the steps finished to before this time.
Aggregation would work exactly the same.
Display of the project status in the reporting app could be:
 - as a separate project status page.
 - as coloring for the cells that have not changed since the last time point.

**Comment by lukbut** [comment]
@tcezard Let's have a little chat soon please about how you imagine this implemented.

**Comment by lukbut** [comment]
Yesterday, Tim and I agreed that this issue should focus on changes in rest_api/limsdb/queries/factories.py get_samples_and_processes(), possibly also in get_sample_in_queues_or_progress(). It is important to note that the new functionality delivered in this change will likely only be able to display completed statuses at a prior time. UDF content, as well as any queue statuses which have since changed are not planned to be shown as this information is not efficiently logged at present.

**Comment by lukbut** [comment]
An initial version of this implementation has been deployed to the development server by @tcezard today, and will be reviewed by @EGCGDanForth.
